### PR TITLE
Loeffler: exercise-05

### PR DESCRIPTION
**Pull request by MagLoe1**

### CODE REVIEW

**Comment by TeraBT** [comment]
Hey, Mag! I was wondering what this code snippet of yours exactly does:

`f.write(f"{rank},{l[0]},{l[1]},{l[1]/sum_words}\n")     # f"..." to make formatting easier`

What do the curly braquets do?

**Comment by MagLoe1** [comment]
Hi @TeraBT,
as I wrote in the comment for this snippet, I used this part of the code to make formatting easier (there are also many other methods for formatting, but I really like this one as it is so simple).
If you write an _f_ in front of a string, you can turn it into a formatting string. The advantage of it is, that you can simply insert variables with curly brackets into your string:

Imagine you have two variables, a = 5 and b = 7. Instead of writing
```
print("I know that" a, "is smaller than", b, ".")
I know that 5 is smaller than 7.
```
you could just write it all in one string, and insert the variables `a` and `b `like this:
```
print(f"I know that {a} is smaller than {b}.")
I know that 5 is smaller than 7.
```

So in the second version, you don't have to open and close and open and close strings, because with the curly brackets, `a` and `b` are not seen as a strings but refer to the value you assigned to them. :)

I am not sure if I explained it well, but [here](https://realpython.com/python-f-strings/#simple-syntax) you'll find a proper explanation and also other options to format strings, hope that helps :)

Best regards,
Magdalena

**Comment by TeraBT** [comment]
Thanks a lot! That's a very **_pythonic_** way of doing this and much more straightforward than in C, for instance haha.

```python
print("I know that" a, "is smaller than", b, ".")
```
but this doesn't seem to be valid ;)

**Comment by MagLoe1** [comment]
@TeraBT oops, you are right, thanks for spotting it! Well, it proves that using format strings is just the better option I guess :D. (I'll edit it now, so that in case somebody reads this, he/she it is not confused :) )

**Pull request closed without merging**
